
# [h5000]
# "GPS/Latitude" = "Lat"
# "GPS/Longitude" = "Lon"

# [nmea]
# "Latitude, deg" = { destinationField = "Lat", matchTags = { source = "127" } }
# "Longitude, deg" = { destinationField = "Lon", matchTags = { source = "127" } }
# "COG, deg" = { destinationField = "COG", matchTags = { source = "127" } }
# "SOG, kn" = { destinationField = "SOG", matchTags = { source = "127" } }

[victron]
# "temperature/20/Temperature" = "TemperatureWork"
# "temperature/21/Temperature" = "TemperatureLiving"
# "temperature/22/Temperature" = "TemperatureOutdoor"

"temperature/20/Temperature" = { matchTags = { instance = "dca6325c100e" }, destinationField = "Temperature", destinationTags = { instance = "Work" } }
"temperature/21/Temperature" = { matchTags = { instance = "dca6325c100e" }, destinationField = "Temperature", destinationTags = { instance = "Living" } }
"temperature/22/Temperature" = { matchTags = { instance = "dca6325c100e" }, destinationField = "Temperature", destinationTags = { instance = "Outdoor" } }

# "temperature/Temperature" = { matchTags = { instance = "dca6325c100e", device = "20" }, destinationField = "Temperature", destinationTags = { instance = "Work" } }
# "temperature/Temperature" = { matchTags = { instance = "dca6325c100e", device = "21" }, destinationField = "Temperature", destinationTags = { instance = "Living" } }
# "temperature/Temperature" = { matchTags = { instance = "dca6325c100e", device = "22" }, destinationField = "Temperature", destinationTags = { instance = "Outdoor" } }
